풀이회고

diff --git a/ps_tool b/ps_tool
--- a/ps_tool
+++ b/ps_tool
@@ -1,18 +1,37 @@
 #!/bin/bash
 SOLVING_PROCEDURE=풀이과정.md
-LANGUAGE_EXT=cpp
+SOLVING_REVIEW=풀이회고.md
+LANGUAGE_EXT=(cpp rs)
 
 function new_problem() {
 	DIR_NAME=$1
 
-	mkdir -p $DIR_NAME
+	if [ -z $DIR_NAME ]
+	then
+		echo "Please enter your new problem name."
+		return
+	fi
+
+	if [ $DIR_NAME = 'test' ]
+	then
+		echo "The name cannot be used as a problem name."
+		return
+	fi
+
+	set -e
+	cargo new $DIR_NAME
+	mkdir $DIR_NAME/{input,output}
 	sed "s/problem_name/$DIR_NAME/" ./$SOLVING_PROCEDURE > ./$DIR_NAME/$SOLVING_PROCEDURE
-	touch ./$DIR_NAME/solution.$LANGUAGE_EXT
+	cp ./$SOLVING_REVIEW ./$DIR_NAME/
+
+	touch ./$DIR_NAME/src/solution.$LANGUAGE_EXT
+	cp rustfmt.toml ./$DIR_NAME/
+
+	
+	set +e
 }
 
-
-case $1 in
-	help)
+function help_message() {
 	cat <<HELP
 Usage: ./ps_tool COMMAND
 
@@ -21,12 +40,15 @@ help			show this message
 new problem_name	create new problem solving necessaries.
 
 HELP
-	;;
+}
+
+
+case $1 in
 	new)
 	shift 1
 	new_problem $@
 	;;
 	*)
-	echo "'$1' command is not supported"
+	help_message
 	;;
 esac
